version: "3"

networks:
  stack_ponte:
    external: true

services:
  frontend_alojona:
    container_name: "alojona"
    image: webdevops/apache
    working_dir: /app
    volumes:
      - "${PATHPESSOAL}/alojona:/app"
    networks:
      - stack_ponte
    ports:
      - "3100:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alojona.rule=Host(`www.${DOMAIN}`,`${DOMAIN}`)"
      - traefik.http.services.alojona.loadbalancer.server.port=80
      - "traefik.http.routers.alojona.tls.certresolver=le"